const $=s=>document.querySelector(s);const $$=s=>Array.from(document.querySelectorAll(s));
const STORAGE_KEY='koreanGrammarNoRedinkProgress.v1';
let state=loadState();let currentGrammar=null;let currentRound=1;let practice=[];let qIndex=0;let answers=[];
function loadState(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY))||{progress:{},wrong:[],settings:{}}}catch(e){return{progress:{},wrong:[],settings:{}}}}
function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state));renderStats();renderToday();}
function p(id){return state.progress[id]||(state.progress[id]={round:0,score:0,diagnosed:false,known:false,last:null,next:null,mastered:false})}
function todayISO(){return new Date().toISOString().slice(0,10)}
function daysFromNow(n){let d=new Date();d.setDate(d.getDate()+n);return d.toISOString().slice(0,10)}
function show(view){$$('.view').forEach(v=>v.classList.remove('active'));$('#'+view).classList.add('active');$$('.nav').forEach(b=>b.classList.toggle('active',b.dataset.view===view));if(view==='library')renderLibrary();if(view==='review')renderReview();if(view==='wrongbook')renderWrong();window.scrollTo({top:0,behavior:'smooth'});}
$$('[data-view]').forEach(b=>b.addEventListener('click',()=>show(b.dataset.view)));$$('.jump').forEach(b=>b.addEventListener('click',()=>show(b.dataset.view)));
function renderStats(){let total=GRAMMARS.length, learning=0, mastered=0;Object.values(state.progress).forEach(x=>{if(x.round>0&&!x.mastered)learning++;if(x.mastered)mastered++;});$('#statTotal').textContent=total;$('#statLearning').textContent=learning;$('#statMastered').textContent=mastered;$('#statWrong').textContent=state.wrong.length;}
function dueList(){let t=todayISO();return GRAMMARS.filter(g=>{let pr=p(g.id);return pr.round>0&&!pr.mastered&&(!pr.next||pr.next<=t)}).sort((a,b)=>p(a.id).next?.localeCompare(p(b.id).next||'')||a.id-b.id)}
function renderToday(){let list=dueList().slice(0,6);let box=$('#todayList');if(!box)return;if(!list.length){box.innerHTML='<div class="mini">暂无到期复习。可以从语法库开始一个新语法点。</div>';return}box.innerHTML=list.map(g=>`<div class="mini"><span><b>${g.title}</b><br><small>第 ${Math.min(p(g.id).round+1,6)} 次复习</small></span><button onclick="openLesson(${g.id})">开始</button></div>`).join('')}
function card(g){let pr=p(g.id), pct=pr.mastered?100:Math.min(pr.round/6*100,100);return `<article class="grammar-card"><div><span class="badge">${g.level}</span></div><h3 class="korean">${g.id}. ${g.title}</h3><p>${g.meaning_cn}</p><div class="progressbar"><span style="width:${pct}%"></span></div><small>进度：${pr.mastered?'已掌握':`第 ${pr.round}/6 次完成`} ${pr.next?' · 下次 '+pr.next:''}</small><div class="card-actions"><button class="primary" onclick="openLesson(${g.id})">进入</button><button class="secondary" onclick="startRound(${g.id},0)">先诊断</button></div></article>`}
function renderLibrary(){let q=$('#search').value.trim().toLowerCase();let lv=$('#levelFilter').value;let arr=GRAMMARS.filter(g=>(!q||(g.title+g.meaning_cn+g.meaning_en+g.form).toLowerCase().includes(q))&&(!lv||g.level.includes(lv)));$('#grammarList').innerHTML=arr.map(card).join('')||'<div class="card">没搜到。</div>'}
$('#search').addEventListener('input',renderLibrary);$('#levelFilter').addEventListener('change',renderLibrary);$('#resetFilters').addEventListener('click',()=>{$('#search').value='';$('#levelFilter').value='';renderLibrary()});
window.openLesson=function(id){currentGrammar=GRAMMARS.find(g=>g.id===id);let pr=p(id);let chatPrompt=encodeURIComponent(`我正在做韩语 NoRedInk 式语法练习。语法点：${currentGrammar.title}。请先诊断我会不会；如果不会，请按我给过的资料风格总结用法（中文+English），然后生成 6 次复习：1讲解+基础题，2变形+填空，3对话+改错，4阅读+O/X，5混合题，6自由输出+批改。题目要纯实践，不要泛泛理论。`);$('#lessonBox').innerHTML=`<div class="card lesson-head"><div><h1 class="korean">${currentGrammar.title}</h1><div class="meta"><span class="badge">${currentGrammar.level}</span><span class="badge">${pr.diagnosed?pr.known?'诊断：会':'诊断：需学习':'未诊断'}</span><span class="badge">${pr.mastered?'已掌握':`完成 ${pr.round}/6`}</span></div></div><button class="primary" onclick="startRound(${id},${pr.diagnosed?Math.min(pr.round+1,6):0})">${pr.diagnosed?'继续练习':'开始诊断'}</button></div>
<div class="card"><h2>用法讲解</h2><div class="explain-grid"><div><h3>中文</h3><p>${currentGrammar.meaning_cn}</p><p><b>接续：</b><span class="korean"> ${currentGrammar.form}</span></p><p><b>语感：</b>${currentGrammar.nuance}</p></div><div><h3>English</h3><p>${currentGrammar.meaning_en}</p><p><b>Form:</b> <span class="korean">${currentGrammar.form}</span></p><p><b>Nuance:</b> ${currentGrammar.nuance}</p></div></div></div>
<div class="card"><h2>例句</h2>${currentGrammar.examples.map(e=>`<div class="example"><b class="korean">${e[0]}</b><span>${e[1]}</span></div>`).join('')}</div>
<div class="card"><h2>易错点</h2><ul>${currentGrammar.pitfalls.map(x=>`<li>${x}</li>`).join('')}</ul></div>
<div class="card"><h2>6 次复习轨道</h2><div class="rounds">${[1,2,3,4,5,6].map(n=>`<button class="round ${pr.round>=n?'done':''} ${pr.round+1===n?'current':''}" onclick="startRound(${id},${n})">${n}<br><small>${roundName(n)}</small></button>`).join('')}</div><p style="margin-top:18px"><a target="_blank" href="https://chatgpt.com/?q=${chatPrompt}">打开 ChatGPT：针对这个语法生成/批改练习 ↗</a></p></div>`;show('lesson')}
function roundName(n){return ['','讲解+基础','变形+填空','对话+改错','阅读+O/X','混合','自由输出'][n]||'诊断'}
window.startRound=function(id,round){currentGrammar=GRAMMARS.find(g=>g.id===id);currentRound=round||0;practice=makePractice(currentGrammar,currentRound);qIndex=0;answers=[];renderPractice();show('practice')}
$('#backToLesson').addEventListener('click',()=>currentGrammar?openLesson(currentGrammar.id):show('library'));
function makePractice(g,round){if(round===0)return diagnostic(g);if(round===1)return basics(g);if(round===2)return transformFill(g);if(round===3)return dialogueCorrection(g);if(round===4)return readingOX(g);if(round===5)return mixed(g);return outputTask(g)}
function stem(g){return g.title.replace(/（.*?）/g,'')}
function diagnostic(g){return [{type:'choice',title:'诊断 1：这个语法大概表达什么？',prompt:`${g.title}`,options:[g.meaning_cn,'尊敬体终结词尾','只表示过去完成','只表示否定禁止'],answer:0,why:'先看你是否能把形式和核心意义连上。'},
{type:'choice',title:'诊断 2：接续判断',prompt:`哪一个最接近正确接续？`,options:[g.form,'N만 + 고 싶다','A/V + 입니다 + 고','过去词干 + 이에요만'],answer:0,why:'NoRedInk 式第一步：先确认 form。'},
{type:'text',title:'诊断 3：造一个韩语短句',prompt:`请用「${stem(g)}」写一个你日常会用的句子。`,sample:g.examples[0][0],why:'能输出才算真的会。'},
{type:'self',title:'诊断 4：自评',prompt:'你看到这个语法时的真实状态？',options:['完全不会，需要讲解','看得懂但不会用','会做题但不自然','能自然输出'],why:'自适应入口：低于“自然输出”就进入第 1 次。'}]}
function basics(g){return [{type:'choice',title:'基础 1：意义识别',prompt:`${g.examples[0][0]}`,options:[g.examples[0][1],'我明天会买这个。','请不要这样做。','这件事不可能发生。'],answer:0,why:'先把语法意义和真实句子对应。'},
{type:'choice',title:'基础 2：选择自然句',prompt:'选出最自然的一句。',options:[g.examples[1][0],g.examples[1][0].replace(/요\.?$/,' 입니다.'),stem(g)+' 저는 카페예요.', '저는 '+stem(g)+' 좋아요.'],answer:0,why:'不是背理论，而是识别自然韩语。'},
{type:'text',title:'基础 3：套用例句',prompt:`仿照例句改写：${g.examples[0][0]}\n主题：韩语学习 / 复习 / 作业`,sample:g.examples[0][0],why:'从模仿开始，降低输出压力。'}]}
function transformFill(g){let f=stem(g);return [{type:'text',title:'变形 1：接续变形',prompt:`把括号里的词接成「${f}」形式：\n공부하다 → ______`,sample:`공부하다 + ${f}`,why:'此处重点检查词干接续，答案可复制给 ChatGPT 精批。'},
{type:'text',title:'填空 2：完成句子',prompt:`한국어를 자연스럽게 말____ 매일 듣기 연습을 해요.\n请填入最合适的语法形式。`,sample:g.examples[0][0],why:'把语法放进目的/原因/背景等真实功能里。'},
{type:'text',title:'填空 3：按中文写韩语',prompt:`中文：因为/为了/虽然/做完……等，请根据「${g.title}」的意义写一句完整韩语。`,sample:g.examples[1][0],why:'中文提示只是语义支架，目标是韩语完整句。'}]}
function dialogueCorrection(g){return [{type:'text',title:'对话 1：完成回应',prompt:`A: 요즘 한국어 공부가 어때요?\nB: ${g.title}를 써서 자연스럽게 대답해 보세요.`,sample:g.examples[1][0],why:'对话题训练“什么时候该用”。'},
{type:'text',title:'改错 2：找出不自然处并改写',prompt:`틀린 문장: 저는 한국어를 잘해요 ${stem(g)} 매일 연습해요.\n请改成自然句。`,sample:g.examples[0][0],why:'改错比选择题更接近 NoRedInk 的操作题。'},
{type:'choice',title:'对话 3：选择更自然的后句',prompt:`A: 내일 시험이 있어요.\nB: ______`,options:[`그럼 오늘 복습해야 해요.`,`그럼 의자부터 예뻐요.`,`그럼 책상인데 먹었어요.`,`그럼 어제만 영화예요.`],answer:0,why:'先抓语义逻辑，再抓语法形式。'}]}
function readingOX(g){return [{type:'choice',title:'阅读 O/X 1',prompt:`읽기: ${g.examples[0][0]}\n意思是否接近：${g.examples[0][1]}`,options:['O','X'],answer:0,why:'阅读里先确认语法承担的语义。'},
{type:'choice',title:'阅读 O/X 2',prompt:`읽기: ${g.examples[1][0]}\n这个句子完全不能用于日常对话。`,options:['O','X'],answer:1,why:'多数例句是日常可用句，要训练语境判断。'},
{type:'text',title:'阅读后输出 3',prompt:`读完两个例句后，请用「${g.title}」总结你今天的学习状态。`,sample:`오늘은 ${g.title}를 연습했어요.`,why:'阅读题最后要转回主动输出。'}]}
function mixed(g){return [...basics(g).slice(0,1),...transformFill(g).slice(0,1),...dialogueCorrection(g).slice(0,1),...readingOX(g).slice(0,1),{type:'text',title:'混合 5：微写作',prompt:`用「${g.title}」写 2 句：一句关于学习，一句关于日常/朋友/韩国生活。`,sample:g.examples.map(x=>x[0]).join('\n'),why:'第 5 次用混合题检查是否脱离单一题型。'}]}
function outputTask(g){return [{type:'output',title:'第 6 次：自由输出 + ChatGPT 批改',prompt:`请写 80–120 字韩语小段文，至少使用 2 次「${g.title}」。主题从下面选一个：\n1. 今天的韩语学习\n2. 韩国生活中的一个小困扰\n3. 一个你想做的创作/女团企划/视频计划\n写完后点击“复制批改指令”。`,sample:`请批改我的韩语段文，重点检查语法「${g.title}」是否自然。请按：1错误处 2为什么错 3更自然表达 4同语法再出3题 的格式回复。`,why:'最终目标是自由输出，不是只会选择题。'}]}
function renderPractice(){let q=practice[qIndex];let done=qIndex>=practice.length;if(done){finishRound();return}let progress=`${qIndex+1}/${practice.length}`;let body='';if(q.type==='choice'||q.type==='self'){body=`<div class="options">${q.options.map((o,i)=>`<button class="option" onclick="choose(${i})">${o}</button>`).join('')}</div>`}else if(q.type==='text'){body=`<textarea id="textAnswer" placeholder="在这里写答案。网站会给基础反馈；精批请复制给 ChatGPT。"></textarea><button class="primary" onclick="submitText()">提交</button><details><summary>参考方向</summary><p class="korean">${q.sample}</p></details>`}else{let prompt=encodeURIComponent(`${q.sample}\n\n我的段文：`);body=`<textarea id="outputAnswer" placeholder="写 80–120 字韩语段文"></textarea><button class="primary" onclick="copyOutputPrompt()">复制批改指令</button> <a target="_blank" href="https://chatgpt.com/?q=${prompt}">打开 ChatGPT 批改 ↗</a>`}
$('#practiceBox').innerHTML=`<div class="card"><p class="eyebrow">${currentGrammar.title} · ${currentRound?`第 ${currentRound} 次 ${roundName(currentRound)}`:'诊断'} · ${progress}</p><h1>${q.title}</h1><div class="question"><div class="q-title korean">${q.prompt.replace(/\n/g,'<br>')}</div>${body}<div id="fb"></div></div></div>`}
window.choose=function(i){let q=practice[qIndex];$$('.option').forEach((b,idx)=>{b.classList.toggle('selected',idx===i);if(q.type==='choice'){b.classList.toggle('correct',idx===q.answer);if(idx===i&&idx!==q.answer)b.classList.add('wrong')}});let ok=q.type==='self'? i>=2 : i===q.answer;answers.push({ok,question:q.title,prompt:q.prompt,answer:q.options[i],correct:q.options[q.answer]||'自评',grammar:currentGrammar.title,round:currentRound});if(!ok&&q.type!=='self')addWrong(q,q.options[i],q.options[q.answer]);$('#fb').innerHTML=`<div class="feedback ${ok?'good':'bad'}"><b>${ok?'很好！':'这里需要复练。'}</b><br>${q.why}</div><button class="primary" onclick="nextQ()">下一题</button>`}
window.submitText=function(){let q=practice[qIndex];let val=$('#textAnswer').value.trim();let ok=val.length>6 && containsHangul(val);answers.push({ok,question:q.title,prompt:q.prompt,answer:val,correct:q.sample,grammar:currentGrammar.title,round:currentRound});if(!ok)addWrong(q,val,q.sample);$('#fb').innerHTML=`<div class="feedback ${ok?'good':'bad'}"><b>${ok?'已提交。':'答案太短或没有韩文。'}</b><br>${q.why}<br><small>基础检查只判断长度/韩文；自然度请第 6 次或点击 ChatGPT 精批。</small></div><button class="primary" onclick="nextQ()">下一题</button>`}
function containsHangul(s){return /[가-힣]/.test(s)}
window.nextQ=function(){qIndex++;renderPractice()}
function addWrong(q,ans,correct){state.wrong.unshift({time:new Date().toISOString(),grammarId:currentGrammar.id,grammar:currentGrammar.title,round:currentRound,question:q.title,prompt:q.prompt,answer:ans||'(空)',correct:correct||q.sample||'',why:q.why});state.wrong=state.wrong.slice(0,300);save()}
function finishRound(){let ok=answers.filter(a=>a.ok).length, total=answers.length, rate=total?ok/total:1;let pr=p(currentGrammar.id);if(currentRound===0){pr.diagnosed=true;pr.known=rate>=.75;if(pr.known){pr.round=Math.max(pr.round,1);pr.next=daysFromNow(1)}else{pr.round=0;pr.next=todayISO()}}else{if(rate>=.6){pr.round=Math.max(pr.round,currentRound);let gaps=[0,1,3,5,7,14,30];pr.next=currentRound>=6?null:daysFromNow(gaps[currentRound]||3);if(currentRound>=6)pr.mastered=true}else{pr.next=todayISO()}}pr.score=Math.round(rate*100);pr.last=todayISO();save();$('#practiceBox').innerHTML=`<div class="card"><h1>${currentRound?'本轮完成':'诊断完成'} 🎉</h1><p>正确/通过：${ok}/${total}，通过率 ${Math.round(rate*100)}%。</p><p>${currentRound===0?(pr.known?'你可以直接进入复习轨道。':'建议先看讲解，然后做第 1 次。'):(rate>=.6?'已记录进度。':'本轮建议重做一次。')}</p><div class="card-actions"><button class="primary" onclick="openLesson(${currentGrammar.id})">回到语法页</button><button class="secondary" onclick="startRound(${currentGrammar.id},${currentRound?Math.min(currentRound+1,6):1})">继续下一轮</button></div></div>`}
function renderReview(){let arr=dueList();if(!arr.length)arr=GRAMMARS.filter(g=>p(g.id).round>0&&!p(g.id).mastered).slice(0,20);$('#reviewList').innerHTML=arr.length?arr.map(card).join(''):'<p>暂无复习。去语法库开始一个新语法点吧。</p>'}
function renderWrong(){let box=$('#wrongList');if(!state.wrong.length){box.innerHTML='<p>暂时没有错题。</p>';return}box.innerHTML=state.wrong.map((w,i)=>`<div class="wrong-item"><span class="badge">${w.grammar}</span><h3>${w.question}</h3><p class="korean">${String(w.prompt).replace(/\n/g,'<br>')}</p><p><b>你的答案：</b>${w.answer}</p><p><b>参考：</b><span class="korean">${w.correct}</span></p><p>${w.why}</p><button onclick="openLesson(${w.grammarId})">回到语法点</button></div>`).join('')}
$('#startToday').addEventListener('click',()=>{let d=dueList()[0]||GRAMMARS.find(g=>p(g.id).round===0)||GRAMMARS[0];openLesson(d.id)});
$('#exportData').addEventListener('click',()=>{$('#dataBox').value=JSON.stringify(state,null,2);let blob=new Blob([$('#dataBox').value],{type:'application/json'});let a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='korean-grammar-progress.json';a.click()});
$('#importData').addEventListener('change',async e=>{let file=e.target.files[0];if(!file)return;let txt=await file.text();try{state=JSON.parse(txt);save();alert('已导入进度');}catch(err){alert('JSON 格式不对')}});
$('#clearData').addEventListener('click',()=>{if(confirm('确定清空？')){localStorage.removeItem(STORAGE_KEY);state=loadState();save();renderLibrary();renderWrong();}});
renderStats();renderToday();renderLibrary();
